enableNoEmiMessage = true
spawnWithGuideBook = true
respawnWithGuideBook = true
disableFuelTooltips = false
disableItemTagTooltips = false
newVersionMessage = false
enableHatchPlacementOverlay = true
enableBarrelContentRendering = true
colorWaterLava = true
enableDebugCommands = true
enableBidirectionalEnergyCompat = false
enableAe2Integration = true
enableFtbQuestsIntegration = true
enableDefaultOreGenTooltips = true
datagenOnStartup = false
loadRuntimeGeneratedResources = true
removeIndustrialistTrades = false
maxDistillationTowerHeight = 9
enableInterMachineConnectedTextures = false
