version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 20
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 3.4641016
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
powderSnowCulling = true
endGatewayCulling = false
beaconBeamCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
universal_ores = true
fruitfulfun = true
ends_delight = true
farmersdelight = true
expandedstorage = true
nethersdelight = true
botania = true
travelersbackpack = true
ae2 = true
botanypots = true
betterfurnacesreforged = true
moderndynamics = true
extended_drawers = true
chimes = true
ftbquests = true
universal_graves = true
croparia = true
botanypotstiers = true
ad_astra = true
modern_industrialization = true
expandeddelight = true
spontaneous-replace = true
minecraft = true
animal_feeding_trough = true
